on:
    push:
        # Sequence of patterns matched against refs/tags
        tags:
            - "v0.1.2"

env:
    # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
    BUILD_TYPE: Release

name: Create Release

jobs:
    build:
        name: Create Release
        runs-on: ubuntu-latest
        steps:
            - name: Building deb package
              run: |
                  cd ${{ github.workspace }}
                  ./release.sh

            - name: Checkout code
              uses: actions/checkout@v2
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  body: |
                      Added Create App to python TUI
                  draft: false
                  prerelease: false
