env:
    BUILD_TYPE: Release
    tag: "v0.1.2"

on:
    push:
        branches: ["main"]
        tags:
            - "v0.1.2"

name: libaloo releases

jobs:
    build:
        name: libaloo releases
        runs-on: ubuntu-latest
        steps:
            - name: Building deb package
              run: |
                  cd ${{ github.workspace }}
                  echo $(pwd)
                  tree
                  ./release.sh ${{ env.tag }}

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Create Release
              id: create_release
              uses: actions/create-release@v.1.1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  body: |
                      Added Create App to python TUI
                  draft: false
                  prerelease: false
            - name: Lib aloo deb file
              id: upload-release-asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./libaloo-${{ env.tag }}.deb
                  asset_name: libaloo-${{ env.tag }}.deb
                  asset_content_type: application/vnd.debian.binary-package
